import { MatchData, MarketAnalysis } from '@/types/match';
function factorial(n:number):number{if(!Number.isInteger(n)||n<0)return 1;let r=1;for(let i=2;i<=n;i++)r*=i;return r;}
function poisson(lambda:number,k:number):number{if(!Number.isFinite(lambda)||lambda<0||k<0)return 0;return(Math.exp(-lambda)*Math.pow(lambda,k))/factorial(k);}
function poissonOver(lambda:number,line:number):number{if(!Number.isFinite(lambda)||lambda<0)return 0;let c=0;for(let k=0;k<=Math.floor(line);k++)c+=poisson(lambda,k);return Math.max(0,Math.min(1,1-c));}
function pct(v:number):number{return Math.max(0,Math.min(100,Math.round(v*100)));}
/** Neutral Bayesian prior; not observed league data. */
function bayes(value:number,prior:number,n:number,strength=3):number{if(!Number.isFinite(value)||!Number.isFinite(prior)||prior<=0||!Number.isFinite(n)||n<=0)return prior;return(n*value+strength*prior)/(n+strength);}
function resultProbabilities(h:number,a:number){let home=0,draw=0,away=0;for(let i=0;i<=10;i++)for(let j=0;j<=10;j++){const p=poisson(h,i)*poisson(a,j);if(i>j)home+=p;else if(i===j)draw+=p;else away+=p;}const sum=home+draw+away;return sum?{home:home/sum,draw:draw/sum,away:away/sum}:{home:0,draw:0,away:0};}
function realXG(match:MatchData){const h=(match as any).homeStats?.expectedGoals??match.metrics?.xG?.[0],a=(match as any).awayStats?.expectedGoals??match.metrics?.xG?.[1];return{home:typeof h==='number'&&Number.isFinite(h)&&h>=0?h:null,away:typeof a==='number'&&Number.isFinite(a)&&a>=0?a:null};}
function numericOrNull(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function modelLambdas(match:MatchData){
  const h=(match as any).homeStats||{},a=(match as any).awayStats||{};
  const homeN=numericOrNull(match.sampleSize?.homeGames) ?? numericOrNull(h.gamesCount); const awayN=numericOrNull(match.sampleSize?.awayGames) ?? numericOrNull(a.gamesCount); const n=homeN!==null&&awayN!==null?Math.min(homeN,awayN):null;
  const league=numericOrNull(match.modelData?.leagueAvg) ?? numericOrNull(h.leagueAvg) ?? numericOrNull(a.leagueAvg) ?? 2.5;
  const hGF=numericOrNull(match.modelData?.homeGoalsAvg) ?? numericOrNull(h.goalsFor);
  const aGF=numericOrNull(match.modelData?.awayGoalsAvg) ?? numericOrNull(a.goalsFor);
  const hGA=numericOrNull(match.modelData?.homeGoalsAgainstAvg) ?? numericOrNull(h.goalsAgainst);
  const aGA=numericOrNull(match.modelData?.awayGoalsAgainstAvg) ?? numericOrNull(a.goalsAgainst);
  if(!(n!==null&&n>=3&&homeN!==null&&awayN!==null&&league>0&&[hGF,aGF,hGA,aGA].every((v):v is number=>v!==null&&v>=0)))return null;
  const hAttack=bayes(hGF,league,homeN),aDefense=bayes(aGA,league,awayN),aAttack=bayes(aGF,league,awayN),hDefense=bayes(hGA,league,homeN);
  return{home:Math.max(.01,(hAttack/league)*(aDefense/league)*league),away:Math.max(.01,(aAttack/league)*(hDefense/league)*league),n};
}
export interface CanonicalGoalLambdas { homeLambda: number; awayLambda: number; sampleSize: number; leagueAvg: number; }

/** Canonical base goal model used by all market/score consumers. Contextual adjustments belong upstream (e.g. readingEngine). */
export function getCanonicalGoalLambdas(match:MatchData):CanonicalGoalLambdas|null{
  const h=(match as any).homeStats||{},a=(match as any).awayStats||{};
  const homeN=numericOrNull(match.sampleSize?.homeGames) ?? numericOrNull(h.gamesCount); const awayN=numericOrNull(match.sampleSize?.awayGames) ?? numericOrNull(a.gamesCount); const n=homeN!==null&&awayN!==null?Math.min(homeN,awayN):null;
  const league=numericOrNull(match.modelData?.leagueAvg) ?? numericOrNull(h.leagueAvg) ?? numericOrNull(a.leagueAvg) ?? 2.5;
  const hGF=numericOrNull(match.modelData?.homeGoalsAvg) ?? numericOrNull(h.goalsFor);
  const aGF=numericOrNull(match.modelData?.awayGoalsAvg) ?? numericOrNull(a.goalsFor);
  const hGA=numericOrNull(match.modelData?.homeGoalsAgainstAvg) ?? numericOrNull(h.goalsAgainst);
  const aGA=numericOrNull(match.modelData?.awayGoalsAgainstAvg) ?? numericOrNull(a.goalsAgainst);
  if(!(n!==null&&n>=3&&homeN!==null&&awayN!==null&&league>0&&[hGF,aGF,hGA,aGA].every((v):v is number=>v!==null&&v>=0)))return null;
  const hAttack=bayes(hGF,league!,homeN),aDefense=bayes(aGA,league!,awayN),aAttack=bayes(aGF,league!,awayN),hDefense=bayes(hGA,league!,homeN);
  return {homeLambda:Math.max(.01,(hAttack/league!)*(aDefense/league!)*league!),awayLambda:Math.max(.01,(aAttack/league!)*(hDefense/league!)*league!),sampleSize:n,leagueAvg:league!};
}

function add(markets:MarketAnalysis[],market:string,probability:number,risk:string,category:string,source:MarketAnalysis['probabilitySource'],calibration:MarketAnalysis['calibrationStatus']='UNCALIBRATED'){if(!Number.isFinite(probability))return;const p=Math.max(0,Math.min(100,Math.round(probability)));markets.push({market,probability:p,fairOdd:p>0?Math.round((100/p)*100)/100:undefined,risk,category,probabilitySource:source,calibrationStatus:calibration,oddSource:'UNKNOWN'});}
export function isValidBet(probability:number,ev=0):boolean{return Number.isFinite(probability)&&probability>=60&&Number.isFinite(ev)&&ev>=0;}
export interface MarketLambdaOverride { homeLambda: number; awayLambda: number; }

export function analyzeMarkets(match:MatchData, lambdaOverride?: MarketLambdaOverride):MarketAnalysis[]{const markets:MarketAnalysis[]=[];const h=(match as any).homeStats||{},a=(match as any).awayStats||{};const homeN=numericOrNull(match.sampleSize?.homeGames) ?? numericOrNull(h.gamesCount),awayN=numericOrNull(match.sampleSize?.awayGames) ?? numericOrNull(a.gamesCount),n=homeN!==null&&awayN!==null?Math.min(homeN,awayN):null;const league=numericOrNull(match.modelData?.leagueAvg) ?? numericOrNull(h.leagueAvg) ?? numericOrNull(a.leagueAvg) ?? 2.5;const hGF=numericOrNull(match.modelData?.homeGoalsAvg) ?? numericOrNull(h.goalsFor);const aGF=numericOrNull(match.modelData?.awayGoalsAvg) ?? numericOrNull(a.goalsFor);const hGA=numericOrNull(match.modelData?.homeGoalsAgainstAvg) ?? numericOrNull(h.goalsAgainst);const aGA=numericOrNull(match.modelData?.awayGoalsAgainstAvg) ?? numericOrNull(a.goalsAgainst);const modelReady=n!==null&&n>=3&&homeN!==null&&awayN!==null&&league>0&&[hGF,aGF,hGA,aGA].every((v):v is number=>v!==null&&v>=0);const structuralCalibration=modelReady&&n>=5&&match.modelData?.dataQuality==='VALID'?'MODEL_VALIDATED' as const:'UNCALIBRATED' as const;
if(modelReady){const hAttack=bayes(hGF,league!,homeN),aDefense=bayes(aGA,league!,awayN),aAttack=bayes(aGF,league!,awayN),hDefense=bayes(hGA,league!,homeN),baseHomeLambda=Math.max(.01,(hAttack/league!)*(aDefense/league!)*league!),baseAwayLambda=Math.max(.01,(aAttack/league!)*(hDefense/league!)*league!),homeLambda=Number.isFinite(lambdaOverride?.homeLambda)?Math.max(.01,lambdaOverride!.homeLambda):baseHomeLambda,awayLambda=Number.isFinite(lambdaOverride?.awayLambda)?Math.max(.01,lambdaOverride!.awayLambda):baseAwayLambda,total=homeLambda+awayLambda,xg=realXG(match),totalXG=xg.home!==null&&xg.away!==null?xg.home+xg.away:null;let o15=pct(poissonOver(total,1.5)),o25=pct(poissonOver(total,2.5));const o35=pct(poissonOver(total,3.5)),btts=pct((1-Math.exp(-homeLambda))*(1-Math.exp(-awayLambda)));if(totalXG!==null){o15=Math.round(o15*.6+pct(poissonOver(totalXG,1.5))*.4);o25=Math.round(o25*.6+pct(poissonOver(totalXG,2.5))*.4);}add(markets,'Over 0.5 Gols',pct(poissonOver(total,.5)),'Baixo','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Over 1.5 Gols',o15,o15>=80?'Baixo':'Médio','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Over 2.5 Gols',o25,o25>=65?'Médio':'Alto','goals','MODEL_ESTIMATE',structuralCalibration);if(o35>=20)add(markets,'Over 3.5 Gols',o35,'Alto','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Under 2.5 Gols',100-o25,'Alto','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Ambas Marcam',btts,btts>=65?'Médio':'Alto','btts','MODEL_ESTIMATE',structuralCalibration);const r=resultProbabilities(homeLambda,awayLambda);if(r.home>=.35)add(markets,'Vitória Casa',pct(r.home),r.home>=.55?'Médio':'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.draw>=.28)add(markets,'Empate',pct(r.draw),'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.away>=.35)add(markets,'Vitória Fora',pct(r.away),r.away>=.55?'Médio':'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.home+r.draw>=.62)add(markets,'1X (Casa ou Empate)',pct(r.home+r.draw),'Médio','chance_dupla','MODEL_ESTIMATE',structuralCalibration);if(r.away+r.draw>=.62)add(markets,'X2 (Empate ou Fora)',pct(r.away+r.draw),'Médio','chance_dupla','MODEL_ESTIMATE',structuralCalibration);add(markets,'Gol no 1º Tempo',pct(1-Math.exp(-(total*.45))),'Médio','htft','MODEL_ESTIMATE',structuralCalibration);add(markets,'Gol no 2º Tempo',pct(1-Math.exp(-(total*.55))),'Médio','htft','MODEL_ESTIMATE',structuralCalibration);const hc=numericOrNull(match.modelData?.homeCornersAvg),ac=numericOrNull(match.modelData?.awayCornersAvg);if(hc!==null&&ac!==null&&hc>=0&&ac>=0&&n>=5){// 9.8 is a neutral Bayesian prior, not an observed league average.
    const lambda=bayes(hc+ac,9.8,n,4);for(const line of [4.5,5.5,6.5,7.5,8.5]){const p=pct(poissonOver(lambda,line));if(p>=60)add(markets,`Over ${line} Cantos`,p,p>=78?'Baixo':p>=70?'Médio':'Alto','corners','MODEL_ESTIMATE',structuralCalibration);}}const hcard=numericOrNull(match.modelData?.homeCardsAvg),acard=numericOrNull(match.modelData?.awayCardsAvg);if(hcard!==null&&acard!==null&&hcard>=0&&acard>=0&&n>=5){// 4.3 is a neutral Bayesian prior, not an observed league average.
    const lambda=bayes(hcard+acard,4.3,n,4);for(const line of [0.5,1.5,2.5,3.5]){const p=pct(poissonOver(lambda,line));if(p>=60)add(markets,`Over ${line} Cartões`,p,p>=78?'Médio':'Alto','cards','MODEL_ESTIMATE',structuralCalibration);}}}
const live=(match as any).liveStats;if(match.isLive===true&&live){const da0=numericOrNull(live.dangerousAttacks?.[0]),da1=numericOrNull(live.dangerousAttacks?.[1]),sog0=numericOrNull(live.shotsOnGoal?.[0]),sog1=numericOrNull(live.shotsOnGoal?.[1]),corner0=numericOrNull(live.corners?.[0]),corner1=numericOrNull(live.corners?.[1]);if(da0!==null&&da1!==null&&sog0!==null&&sog1!==null&&corner0!==null&&corner1!==null){const da=da0+da1,sog=sog0+sog1,corners=corner0+corner1,pressure=Math.min(100,Math.round(da*.7+sog*6+corners*3));add(markets,'Pressão Ofensiva ao Vivo',0,pressure>=70?'Médio':'Alto','live_pressure','HEURISTIC','UNCALIBRATED');}}
return markets;}

export function exactScoreDistribution(match:MatchData, maxGoals=7){const model=modelLambdas(match);if(!model)return [];const xg=realXG(match);const homeLambda=xg.home!==null?model.home*.6+xg.home*.4:model.home;const awayLambda=xg.away!==null?model.away*.6+xg.away*.4:model.away;const scores:{score:string;probability:number}[]=[];for(let home=0;home<=maxGoals;home++)for(let away=0;away<=maxGoals;away++)scores.push({score:`${home} x ${away}`,probability:poisson(homeLambda,home)*poisson(awayLambda,away)});const total=scores.reduce((s,x)=>s+x.probability,0)||1;return scores.map(x=>({...x,probability:x.probability/total,source:'NEXUS_CORE_POISSON_BAYES'})).sort((a,b)=>b.probability-a.probability).slice(0,8);}
