import { MatchData, MarketAnalysis } from '@/types/match';
function factorial(n:number):number{if(!Number.isInteger(n)||n<0)return 1;let r=1;for(let i=2;i<=n;i++)r*=i;return r;}
function poisson(lambda:number,k:number):number{if(!Number.isFinite(lambda)||lambda<0||k<0)return 0;return(Math.exp(-lambda)*Math.pow(lambda,k))/factorial(k);}
function poissonOver(lambda:number,line:number):number{if(!Number.isFinite(lambda)||lambda<0)return 0;let c=0;for(let k=0;k<=Math.floor(line);k++)c+=poisson(lambda,k);return Math.max(0,Math.min(1,1-c));}
function pct(v:number):number{return Math.max(0,Math.min(100,Math.round(v*100)));}
function bayes(value:number,prior:number,n:number,strength=3):number{if(!Number.isFinite(value)||!Number.isFinite(prior)||prior<=0||!Number.isFinite(n)||n<=0)return prior;return(n*value+strength*prior)/(n+strength);}
function resultProbabilities(h:number,a:number){let home=0,draw=0,away=0;for(let i=0;i<=10;i++)for(let j=0;j<=10;j++){const p=poisson(h,i)*poisson(a,j);if(i>j)home+=p;else if(i===j)draw+=p;else away+=p;}const sum=home+draw+away;return sum?{home:home/sum,draw:draw/sum,away:away/sum}:{home:0,draw:0,away:0};}
function realXG(match:MatchData){const h=(match as any).homeStats?.expectedGoals??match.metrics?.xG?.[0],a=(match as any).awayStats?.expectedGoals??match.metrics?.xG?.[1];return{home:typeof h==='number'&&Number.isFinite(h)&&h>=0?h:null,away:typeof a==='number'&&Number.isFinite(a)&&a>=0?a:null};}
function modelLambdas(match:MatchData){const h=(match as any).homeStats||{},a=(match as any).awayStats||{};const homeN=Number(match.sampleSize?.homeGames??h.gamesCount??0),awayN=Number(match.sampleSize?.awayGames??a.gamesCount??0),n=Math.min(homeN,awayN);const leagueRaw=Number(match.modelData?.leagueAvg??h.leagueAvg??a.leagueAvg??2.5),league=Number.isFinite(leagueRaw)&&leagueRaw>0?leagueRaw:null;const hGF=Number(match.modelData?.homeGoalsAvg??h.goalsFor??NaN),aGF=Number(match.modelData?.awayGoalsAvg??a.goalsFor??NaN),hGA=Number(match.modelData?.homeGoalsAgainstAvg??h.goalsAgainst??NaN),aGA=Number(match.modelData?.awayGoalsAgainstAvg??a.goalsAgainst??NaN);if(!(n>=3&&league!==null&&[hGF,aGF,hGA,aGA].every(Number.isFinite)&&hGF>=0&&aGF>=0&&hGA>=0&&aGA>=0))return null;const hAttack=bayes(hGF,league!,homeN),aDefense=bayes(aGA,league!,awayN),aAttack=bayes(aGF,league!,awayN),hDefense=bayes(hGA,league!,homeN);return{home:Math.max(.01,(hAttack/league!)*(aDefense/league!)*league!),away:Math.max(.01,(aAttack/league!)*(hDefense/league!)*league!),n};}
function add(markets:MarketAnalysis[],market:string,probability:number,risk:string,category:string,source:MarketAnalysis['probabilitySource'],calibration:MarketAnalysis['calibrationStatus']='UNCALIBRATED'){if(!Number.isFinite(probability))return;markets.push({market,probability:Math.max(0,Math.min(100,Math.round(probability))),risk,category,probabilitySource:source,calibrationStatus:calibration});}
export function isValidBet(probability:number,ev=0):boolean{return Number.isFinite(probability)&&probability>=60&&Number.isFinite(ev)&&ev>=0;}
export function analyzeMarkets(match:MatchData):MarketAnalysis[]{const markets:MarketAnalysis[]=[];const h=(match as any).homeStats||{},a=(match as any).awayStats||{};const homeN=Number(match.sampleSize?.homeGames??h.gamesCount??0),awayN=Number(match.sampleSize?.awayGames??a.gamesCount??0),n=Math.min(homeN,awayN);const leagueRaw=Number(match.modelData?.leagueAvg??h.leagueAvg??a.leagueAvg??2.5),league=Number.isFinite(leagueRaw)&&leagueRaw>0?leagueRaw:null;const hGF=Number(match.modelData?.homeGoalsAvg??h.goalsFor??NaN),aGF=Number(match.modelData?.awayGoalsAvg??a.goalsFor??NaN),hGA=Number(match.modelData?.homeGoalsAgainstAvg??h.goalsAgainst??NaN),aGA=Number(match.modelData?.awayGoalsAgainstAvg??a.goalsAgainst??NaN);const modelReady=n>=3&&league!==null&&[hGF,aGF,hGA,aGA].every(Number.isFinite)&&hGF>=0&&aGF>=0&&hGA>=0&&aGA>=0;const structuralCalibration=modelReady&&n>=5&&match.modelData?.dataQuality==='VALID'?'MODEL_VALIDATED' as const:'UNCALIBRATED' as const;
if(modelReady){const hAttack=bayes(hGF,league!,homeN),aDefense=bayes(aGA,league!,awayN),aAttack=bayes(aGF,league!,awayN),hDefense=bayes(hGA,league!,homeN),homeLambda=Math.max(.01,(hAttack/league!)*(aDefense/league!)*league!),awayLambda=Math.max(.01,(aAttack/league!)*(hDefense/league!)*league!),total=homeLambda+awayLambda,xg=realXG(match),totalXG=xg.home!==null&&xg.away!==null?xg.home+xg.away:null;let o15=pct(poissonOver(total,1.5)),o25=pct(poissonOver(total,2.5));const o35=pct(poissonOver(total,3.5)),btts=pct((1-Math.exp(-homeLambda))*(1-Math.exp(-awayLambda)));if(totalXG!==null){o15=Math.round(o15*.6+pct(poissonOver(totalXG,1.5))*.4);o25=Math.round(o25*.6+pct(poissonOver(totalXG,2.5))*.4);}add(markets,'Over 0.5 Gols',pct(poissonOver(total,.5)),'Baixo','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Over 1.5 Gols',o15,o15>=80?'Baixo':'Médio','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Over 2.5 Gols',o25,o25>=65?'Médio':'Alto','goals','MODEL_ESTIMATE',structuralCalibration);if(o35>=20)add(markets,'Over 3.5 Gols',o35,'Alto','goals','MODEL_ESTIMATE',structuralCalibration);add(markets,'Under 2.5 Gols',100-o25,'Alto','goals','DERIVED','UNCALIBRATED');add(markets,'Ambas Marcam',btts,btts>=65?'Médio':'Alto','btts','MODEL_ESTIMATE',structuralCalibration);const r=resultProbabilities(homeLambda,awayLambda);if(r.home>=.35)add(markets,'Vitória Casa',pct(r.home),r.home>=.55?'Médio':'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.draw>=.28)add(markets,'Empate',pct(r.draw),'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.away>=.35)add(markets,'Vitória Fora',pct(r.away),r.away>=.55?'Médio':'Alto','result','MODEL_ESTIMATE',structuralCalibration);if(r.home+r.draw>=.62)add(markets,'1X (Casa ou Empate)',pct(r.home+r.draw),'Médio','chance_dupla','MODEL_ESTIMATE',structuralCalibration);if(r.away+r.draw>=.62)add(markets,'X2 (Empate ou Fora)',pct(r.away+r.draw),'Médio','chance_dupla','MODEL_ESTIMATE',structuralCalibration);add(markets,'Gol no 1º Tempo',pct(1-Math.exp(-(total*.45))),'Médio','htft','MODEL_ESTIMATE',structuralCalibration);add(markets,'Gol no 2º Tempo',pct(1-Math.exp(-(total*.55))),'Médio','htft','MODEL_ESTIMATE',structuralCalibration);const hc=Number(match.modelData?.homeCornersAvg),ac=Number(match.modelData?.awayCornersAvg);if(Number.isFinite(hc)&&Number.isFinite(ac)&&hc>=0&&ac>=0&&n>=5){const lambda=bayes(hc+ac,9.8,n,4),o65=pct(poissonOver(lambda,6.5));if(o65>=70)add(markets,'Over 6.5 Cantos',o65,o65>=78?'Baixo':'Médio','corners','MODEL_ESTIMATE',structuralCalibration);}const hcard=Number(match.modelData?.homeCardsAvg),acard=Number(match.modelData?.awayCardsAvg);if(Number.isFinite(hcard)&&Number.isFinite(acard)&&hcard>=0&&acard>=0&&n>=5){const lambda=bayes(hcard+acard,4.3,n,4),o35c=pct(poissonOver(lambda,3.5));if(o35c>=70)add(markets,'Over 3.5 Cartões',o35c,o35c>=78?'Médio':'Alto','cards','MODEL_ESTIMATE',structuralCalibration);}}
const live=(match as any).liveStats;if(match.isLive===true&&live){const da=Number(live.dangerousAttacks?.[0]??0)+Number(live.dangerousAttacks?.[1]??0),sog=Number(live.shotsOnGoal?.[0]??0)+Number(live.shotsOnGoal?.[1]??0),corners=Number(live.corners?.[0]??0)+Number(live.corners?.[1]??0),pressure=Math.min(100,Math.round(da*.7+sog*6+corners*3));add(markets,'Pressão Ofensiva ao Vivo',0,pressure>=70?'Médio':'Alto','live_pressure','HEURISTIC','UNCALIBRATED');}
return markets;}

export function exactScoreDistribution(match:MatchData, maxGoals=7){const model=modelLambdas(match);if(!model)return [];const xg=realXG(match);const homeLambda=xg.home!==null?model.home*.6+xg.home*.4:model.home;const awayLambda=xg.away!==null?model.away*.6+xg.away*.4:model.away;const scores:{score:string;probability:number}[]=[];for(let home=0;home<=maxGoals;home++)for(let away=0;away<=maxGoals;away++)scores.push({score:`${home} x ${away}`,probability:poisson(homeLambda,home)*poisson(awayLambda,away)});const total=scores.reduce((s,x)=>s+x.probability,0)||1;return scores.map(x=>({...x,probability:x.probability/total,source:'NEXUS_CORE_POISSON_BAYES'})).sort((a,b)=>b.probability-a.probability).slice(0,8);}
