import type { MarketAnalysis, MatchData, CalibrationStatus, ProbabilitySource } from '@/types/match';
import { type DataQualityResult } from './dataQualityGate';
export type NexusDecision='SIGNAL'|'CONSERVATIVE'|'INFO_ONLY'|'REJECT'; export type NexusMode='PRE_MATCH'|'LIVE'; export type EvidenceSource='market'|'engine'|'live'|'model';
export interface NexusEvidence{source:EvidenceSource;name:string;value:number;weight?:number;supports?:boolean;}
export interface NexusDecisionInput{match:Pick<MatchData,'id'|'homeTeam'|'awayTeam'|'league'|'isLive'|'status'|'minute'>;mode:NexusMode;confidence?:number|null;markets?:MarketAnalysis[];evidence?:NexusEvidence[];analysisBlocked?:boolean;engineConflict?:boolean;dataQuality?:DataQualityResult|null;calibrationStatus?:CalibrationStatus|null;probabilitySource?:ProbabilitySource|null;}
export interface NexusDecisionOutput{decision:NexusDecision;confidence:number;riskScore:number;selectedMarket:MarketAnalysis|null;reasonCodes:string[];evidenceScore:number;signalEligible:boolean;}
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,Number.isFinite(n)?n:min));const norm=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?clamp(v):null;const valid=(m:MarketAnalysis[])=>m.filter(x=>Number.isFinite(x.probability)&&x.probability>=0&&x.probability<=100);const score=(m:MarketAnalysis[])=>{const v=valid(m).map(x=>x.probability).sort((a,b)=>a-b);if(!v.length)return 0;const i=Math.floor(v.length/2);return v.length%2?v[i]:(v[i-1]+v[i])/2};const spread=(m:MarketAnalysis[])=>{const v=valid(m).map(x=>x.probability).sort((a,b)=>a-b);return v.length>=2?v[v.length-1]-v[0]:null};const evidence=(e:NexusEvidence[])=>{const u=e.map(x=>({v:clamp(x.value),w:Math.max(0,x.weight??1)})).filter(x=>x.w>0);if(!u.length)return 0;const t=u.reduce((s,x)=>s+x.w,0);return Math.round(u.reduce((s,x)=>s+x.v*x.w,0)/t)};const selected=(m:MarketAnalysis[])=>valid(m).sort((a,b)=>b.probability-a.probability)[0]??null;
export function decideNexus(input:NexusDecisionInput):NexusDecisionOutput{const reasons:string[]=[];const confidence=norm(input.confidence);const markets=input.markets??[];const selectedMarket=selected(markets);const best=score(markets);const sp=spread(markets);const ev=evidence(input.evidence??[]);const unverified=markets.some(m=>m.probabilitySource==='HEURISTIC'||m.probabilitySource==='UNKNOWN');const marketImplied=markets.some(m=>m.probabilitySource==='MARKET_IMPLIED');const source=input.probabilitySource??selectedMarket?.probabilitySource??null;const calibration=input.calibrationStatus??selectedMarket?.calibrationStatus??null;
if(!input.match.id||!input.match.homeTeam||!input.match.awayTeam)return{decision:'REJECT',confidence:confidence??0,riskScore:100,selectedMarket:null,reasonCodes:['INVALID_MATCH'],evidenceScore:0,signalEligible:false};if(input.analysisBlocked)return{decision:'REJECT',confidence:confidence??0,riskScore:100,selectedMarket,reasonCodes:['ANALYSIS_BLOCKED'],evidenceScore:ev,signalEligible:false};if(input.dataQuality?.status==='REJECT')return{decision:'REJECT',confidence:confidence??0,riskScore:100,selectedMarket,reasonCodes:[...input.dataQuality.reasons.map(r=>`DATA_${r}`),'DATA_QUALITY_REJECT'],evidenceScore:ev,signalEligible:false};
if(input.dataQuality?.status==='DEGRADED')reasons.push(...input.dataQuality.reasons.map(r=>`DATA_${r}`),'DATA_QUALITY_DEGRADED');if(input.engineConflict)reasons.push('ENGINE_CONFLICT');if(confidence===null)reasons.push('CONFIDENCE_MISSING');if(ev<55)reasons.push('INSUFFICIENT_EVIDENCE');if(!selectedMarket)reasons.push('NO_VALID_MARKET');else if(best<72)reasons.push('MARKET_BELOW_THRESHOLD');if(sp!==null&&sp>15)reasons.push('MARKET_DISAGREEMENT');if(unverified)reasons.push('PROBABILITY_UNVERIFIED');if(marketImplied)reasons.push('MARKET_IMPLIED_NOT_MODEL_PROBABILITY');if(source!=='MODEL_ESTIMATE')reasons.push('PROBABILITY_SOURCE_NOT_MODEL');if(calibration!=='CALIBRATED')reasons.push('PROBABILITY_NOT_CALIBRATED');if(input.mode==='LIVE'&&input.match.isLive!==true)reasons.push('LIVE_STATE_UNCONFIRMED');
if(confidence===null)return{decision:'INFO_ONLY',confidence:0,riskScore:80,selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(confidence<50||ev<55||!selectedMarket)return{decision:'REJECT',confidence,riskScore:clamp(100-Math.min(confidence,ev)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(confidence<70||best<72)return{decision:'INFO_ONLY',confidence,riskScore:clamp(100-Math.min(confidence,best)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(input.mode==='LIVE'&&input.match.isLive!==true)return{decision:'CONSERVATIVE',confidence,riskScore:clamp(100-Math.min(confidence,best,ev)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(unverified||marketImplied||source!=='MODEL_ESTIMATE'||calibration!=='CALIBRATED')return{decision:'CONSERVATIVE',confidence,riskScore:clamp(100-Math.min(confidence,best,ev)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(input.engineConflict||input.dataQuality?.status==='DEGRADED'||(sp!==null&&sp>15))return{decision:'CONSERVATIVE',confidence,riskScore:clamp(100-Math.min(confidence,best,ev,input.dataQuality?.score??100)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};if(confidence<85){reasons.push('CONSERVATIVE_CONFIDENCE');return{decision:'CONSERVATIVE',confidence,riskScore:clamp(100-Math.min(confidence,best,ev)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:false};}reasons.push('CORE_APPROVED_SIGNAL');return{decision:'SIGNAL',confidence,riskScore:clamp(100-Math.min(confidence,best,ev)),selectedMarket,reasonCodes:reasons,evidenceScore:ev,signalEligible:true};}
export function marketsToNexusEvidence(markets:MarketAnalysis[]):NexusEvidence[]{return markets.filter(m=>Number.isFinite(m.probability)).map(m=>({source:'market',name:m.market,value:clamp(m.probability),weight:1}));}
