// team-stats-ai — optional AI estimate layer. Quantitative core must use observed provider data.
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.1';
import { corsHeaders } from '../_shared/cors.ts';

interface SideStats { possession:number; totalShots:number; shotsOnGoal:number; bigChances:number; corners:number; offsides:number; fouls:number; yellowCards:number; goalsFor:number; goalsAgainst:number; }
const EMPTY:SideStats={possession:0,totalShots:0,shotsOnGoal:0,bigChances:0,corners:0,offsides:0,fouls:0,yellowCards:0,goalsFor:0,goalsAgainst:0};
const sb=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const keyFor=(h:string,a:string)=>`team-stats-ai:v2:${h.toLowerCase()}::${a.toLowerCase()}`;
async function cacheGet(key:string){try{const {data}=await sb().from('cache_api').select('dados_json,ultima_atualizacao').eq('cache_key',key).maybeSingle();if(!data)return null;if(Date.now()-new Date(data.ultima_atualizacao).getTime()>24*3600000)return null;return data.dados_json;}catch{return null;}}
async function cacheSet(key:string,v:any){try{await sb().from('cache_api').upsert({cache_key:key,dados_json:v,ultima_atualizacao:new Date().toISOString()},{onConflict:'cache_key'});}catch{}}
function clean(s:any):SideStats{const n=(v:any,min=0,max=100)=>{const x=Number(v);return Number.isFinite(x)?Math.max(min,Math.min(max,Number(x.toFixed(2)))):0};return{possession:n(s?.possession,0,100),totalShots:n(s?.totalShots,0,50),shotsOnGoal:n(s?.shotsOnGoal,0,30),bigChances:n(s?.bigChances,0,15),corners:n(s?.corners,0,20),offsides:n(s?.offsides,0,15),fouls:n(s?.fouls,0,40),yellowCards:n(s?.yellowCards,0,10),goalsFor:n(s?.goalsFor,0,10),goalsAgainst:n(s?.goalsAgainst,0,10)};}
const system=`Você é um extrator estatístico de futebol. Retorne SOMENTE JSON com médias por jogo dos últimos 5 jogos oficiais de cada equipe. Não invente números ausentes; se não souber um campo, use null. Formato: {"home":{...},"away":{...}}. Campos: possession,totalShots,shotsOnGoal,bigChances,corners,offsides,fouls,yellowCards,goalsFor,goalsAgainst.`;
function normalize(o:any){const side=(s:any)=>{const c=clean(s);for(const k of Object.keys(c) as (keyof SideStats)[])if(s?.[k]===null)c[k]=0;return c};return{home:side(o?.home),away:side(o?.away)};}
async function groq(user:string,key:string){try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'llama-3.3-70b-versatile',messages:[{role:'system',content:system},{role:'user',content:user}],response_format:{type:'json_object'},temperature:0.1,max_tokens:1600})});if(!r.ok)return null;const d=await r.json();return d?.choices?.[0]?.message?.content||null;}catch{return null;}}
async function gemini(user:string,key:string){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${key}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:user}]}],generationConfig:{temperature:0.1,responseMimeType:'application/json'}})});if(!r.ok)return null;const d=await r.json();return(d?.candidates?.[0]?.content?.parts??[]).map((p:any)=>p?.text??'').join('')||null;}catch{return null;}}
function parse(raw:string){try{return JSON.parse(raw.replace(/^```json/i,'').replace(/```$/i,'').trim());}catch{return null;}}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});try{const b=await req.json().catch(()=>({}));const home=String(b?.home||'').trim(),away=String(b?.away||'').trim(),league=String(b?.league||'').trim();if(!home||!away)return new Response(JSON.stringify({error:'missing_teams'}),{status:400,headers:{...corsHeaders,'Content-Type':'application/json'}});const key=keyFor(home,away);const cached=await cacheGet(key);if(cached)return new Response(JSON.stringify({ok:true,source:'ai-cache',...cached}),{headers:{...corsHeaders,'Content-Type':'application/json'}});const user=`Partida: ${home} vs ${away}${league?` (${league})`:''}. Extraia somente médias que sejam sustentadas por conhecimento confiável; não transforme estimativa em fato observado.`;const groqKey=Deno.env.get('GROQ_API_KEY'),geminiKey=Deno.env.get('GEMINI_API_KEY');let raw:string|null=null,source='';if(groqKey){raw=await groq(user,groqKey);if(raw)source='groq:llama-3.3-70b-versatile';}if(!raw&&geminiKey){raw=await gemini(user,geminiKey);if(raw)source='gemini-2.5-flash';}const parsed=raw?parse(raw):null;if(!parsed)return new Response(JSON.stringify({ok:false,source:'ai_unavailable',home:EMPTY,away:EMPTY}),{status:200,headers:{...corsHeaders,'Content-Type':'application/json'}});const out=normalize(parsed);await cacheSet(key,out);return new Response(JSON.stringify({ok:true,source,...out,observed:false}),{headers:{...corsHeaders,'Content-Type':'application/json'}});}catch(e){return new Response(JSON.stringify({ok:false,error:e instanceof Error?e.message:'internal_error',home:EMPTY,away:EMPTY}),{status:200,headers:{...corsHeaders,'Content-Type':'application/json'}});}});
