#!/usr/bin/env bash
# NEXUS 33 — verificação pré-migração. Não altera a stack.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."&&pwd)";cd "$ROOT"
OK=0;FAIL=0;WARN=0
ok(){ echo -e "  \033[1;32m✔\033[0m $*";OK=$((OK+1));};bad(){ echo -e "  \033[1;31m✘\033[0m $*";FAIL=$((FAIL+1));};warn(){ echo -e "  \033[1;33m!\033[0m $*";WARN=$((WARN+1));};sec(){ echo -e "\n\033[1;36m$*\033[0m";}
sec '1. Arquivos do kit';for f in Dockerfile deploy/nginx.conf deploy/Caddyfile deploy/docker-compose.yml deploy/install-vps.sh deploy/apply-migrations.sh deploy/sync-functions.sh deploy/fix-secrets.sh deploy/fix-cron.sh deploy/import-users.sh deploy/set-secrets.sh deploy/update.sh deploy/backup.sh deploy/verify.sh deploy/.env.example SELF-HOST.md TROUBLESHOOTING.md;do [ -f "$f" ]&&ok "$f"||bad "faltando: $f";done
sec '2. Conteúdo';NF=$(ls -d supabase/functions/*/ 2>/dev/null|wc -l);NM=$(ls supabase/migrations/*.sql 2>/dev/null|wc -l);[ "$NF" -gt 0 ]&&ok "$NF edge functions"||bad 'nenhuma edge function';[ "$NM" -gt 0 ]&&ok "$NM migrations"||bad 'nenhuma migration';grep -rl 'yeyctdphzrmyxgskehru' supabase/migrations >/dev/null 2>&1&&warn 'há migration(s) com project-ref histórico'||ok 'nenhum project-ref histórico nas migrations'
sec '3. deploy/.env';if [ ! -f deploy/.env ];then bad 'deploy/.env ausente';else set -a;. deploy/.env;set +a;for K in APP_DOMAIN API_DOMAIN;do [ -n "${!K:-}" ]&&ok "$K=${!K}"||bad "$K vazio";done;fi
sec '4. Secrets';VAULT="${NEXUS33_VAULT:-/etc/nexus33/secrets.env}";[ -f "$VAULT" ]&&{ ok "cofre $VAULT presente";set -a;. "$VAULT";set +a; }||warn "cofre $VAULT ausente — rode deploy/set-secrets.sh";declare -A WHY=([SPORTSRC_API_KEY]='futebol' [FOOTBALL_DATA_ORG_KEY]='fallback futebol' [GEMINI_API_KEY]='pesquisa e auditoria IA' [GROQ_API_KEY]='auditoria IA' [TELEGRAM_BOT_TOKEN]='Telegram' [TELEGRAM_CHAT_ID]='Telegram');for K in SPORTSRC_API_KEY FOOTBALL_DATA_ORG_KEY GEMINI_API_KEY GROQ_API_KEY TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID;do [ -n "${!K:-}" ]&&ok "$K (${WHY[$K]})"||bad "$K vazio";done;for K in TELEGRAM_ADMIN_CHAT_ID TELEGRAM_API_KEY;do [ -n "${!K:-}" ]&&ok "$K definido"||warn "$K vazio (opcional)";done
sec '5. Ambiente';command -v docker >/dev/null 2>&1&&ok docker||warn 'docker ausente';docker compose version >/dev/null 2>&1&&ok 'docker compose v2'||warn 'docker compose v2 ausente';command -v git >/dev/null 2>&1&&ok git||bad 'git ausente';command -v openssl >/dev/null 2>&1&&ok openssl||bad 'openssl ausente';command -v python3 >/dev/null 2>&1&&ok python3||bad 'python3 ausente'
sec '6. DNS';if [ -n "${APP_DOMAIN:-}" ];then IP=$(curl -s --max-time 5 https://api.ipify.org||echo '');for D in "$APP_DOMAIN" "${API_DOMAIN:-}";do [ -z "$D" ]&&continue;R=$(getent ahostsv4 "$D" 2>/dev/null|awk 'NR==1{print $1}');[ -z "$R" ]&&bad "$D não resolve"||{ [ -n "$IP" ]&&[ "$R" != "$IP" ]&&warn "$D → $R (IP local: $IP)"||ok "$D → $R";};done;fi
sec '7. Stack';if [ -d supabase-docker ];then ok 'supabase-docker presente';grep -q NEXUS33_CONFIGURED supabase-docker/.env 2>/dev/null&&ok 'chaves Supabase geradas'||warn 'chaves Supabase ainda não geradas';[ -f supabase-docker/docker-compose.override.yml ]&&ok 'override de secrets presente'||warn 'override ausente — rode deploy/fix-secrets.sh';else warn 'primeira instalação';fi
sec 'Resumo';echo "  OK: $OK   Avisos: $WARN   Erros: $FAIL";[ "$FAIL" -eq 0 ]&&echo 'Pronto para instalação/atualização.'||echo 'Corrija os erros acima antes de instalar.';exit 0
