import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Crown, Crosshair, Loader2, RefreshCw, Target, Trophy } from 'lucide-react';
import { fetchMultiDayMatches } from '@/services/footballApi';
import { analyzeMarkets, exactScoreDistribution } from '@/lib/matchAnalysis';

const shell = 'min-h-screen text-white pb-10 font-sans';
const card = 'rounded-2xl border border-white/10 bg-black/25 backdrop-blur-sm';
function useAnalyticalMatches() { return useQuery({ queryKey: ['nexus-analytical-tools-matches'], queryFn: () => fetchMultiDayMatches(6), staleTime: 1000 * 60 * 30 }); }
function MatchName({ match }: { match: any }) { return <>{match.homeTeam || match.teams?.home?.name || 'Casa'} <span className="text-orange-500/60">vs</span> {match.awayTeam || match.teams?.away?.name || 'Fora'}</>; }
function Loading({ text = 'Carregando jogos...' }) { return <div className="flex items-center justify-center py-20 text-gray-400"><Loader2 className="mr-2 h-5 w-5 animate-spin text-orange-400" />{text}</div>; }
function Empty() { return <div className="py-16 text-center text-gray-500">Nenhum jogo com dados suficientes foi encontrado.</div>; }

export function BingoVIPPro() { const { data = [], isLoading, isError, refetch } = useAnalyticalMatches(); const rows = useMemo(() => (data as any[]).map((m) => ({ match: m, markets: analyzeMarkets(m as any).filter(x => x.probability >= 70 && x.probability > 0).sort((a,b) => b.probability-a.probability).slice(0,3) })).filter(x => x.markets.length).sort((a,b) => (b.markets[0]?.probability||0)-(a.markets[0]?.probability||0)).slice(0,12), [data]); return <div className={shell}><main className="container max-w-6xl mx-auto px-4 py-6"><header className="flex items-center justify-between mb-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-500/15 p-3"><Trophy className="h-6 w-6 text-orange-400" /></div><div><h1 className="text-2xl font-black text-orange-400">BINGO VIP PRO</h1><p className="text-xs text-gray-500">Seleção analítica de múltiplos mercados • motor quantitativo atual</p></div></div><button onClick={() => refetch()} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><RefreshCw className="inline h-3.5 w-3.5 mr-1" />Atualizar</button></header>{isError && <div className="mb-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300"><AlertTriangle className="inline h-4 w-4 mr-2" />Não foi possível carregar os jogos.</div>}{isLoading ? <Loading /> : rows.length === 0 ? <Empty /> : <div className="grid gap-3">{rows.map(({match,markets}: any) => <section key={String(match.id || match.fixture?.id)} className={card+' p-4'}><div className="mb-3 flex items-center justify-between"><div className="font-bold text-sm"><MatchName match={match} /></div><span className="text-[10px] text-gray-500">{match.league?.name || match.league || ''}</span></div><div className="grid gap-2 md:grid-cols-3">{markets.map((m:any) => <div key={m.market} className="rounded-xl border border-orange-500/20 bg-orange-500/5 p-3"><div className="text-xs text-gray-300">{m.market}</div><div className="mt-1 text-xl font-black text-emerald-400">{m.probability}%</div><div className="text-[10px] text-gray-500">{m.risk} • {m.probabilitySource}</div></div>)}</div></section>)}</div>}</main></div>; }

export function ElitePerformance() { const { data = [], isLoading, refetch } = useAnalyticalMatches(); const rows = useMemo(() => (data as any[]).map(m => { const markets=analyzeMarkets(m as any); const goals=Math.max(0,...markets.filter(x=>x.category==='goals').map(x=>x.probability)); const corners=Math.max(0,...markets.filter(x=>x.category==='corners').map(x=>x.probability)); const cards=Math.max(0,...markets.filter(x=>x.category==='cards').map(x=>x.probability)); const score=Math.round(goals*.5+corners*.25+cards*.25); return {m,goals,corners,cards,score}; }).filter(x=>x.score>=65).sort((a,b)=>b.score-a.score).slice(0,20), [data]); return <div className={shell}><main className="container max-w-6xl mx-auto px-4 py-6"><header className="flex items-center justify-between mb-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-amber-500/15 p-3"><Crown className="h-6 w-6 text-amber-400" /></div><div><h1 className="text-2xl font-black text-amber-400">ELITE PERFORMANCE</h1><p className="text-xs text-gray-500">Filtro VIP baseado exclusivamente no motor quantitativo atual</p></div></div><button onClick={() => refetch()} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><RefreshCw className="inline h-3.5 w-3.5 mr-1" />Atualizar</button></header>{isLoading?<Loading/>:rows.length===0?<Empty/>:<div className="grid gap-3">{rows.map(({m,goals,corners,cards,score}:any)=><section key={String(m.id||m.fixture?.id)} className={card+' p-4'}><div className="flex items-center justify-between"><div className="font-bold text-sm"><MatchName match={m}/></div><span className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-xs font-black text-amber-400">ELITE {score}%</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[['Gols',goals],['Escanteios',corners],['Cartões',cards]].map(([label,value]:any)=><div key={label} className="rounded-lg bg-white/5 p-2"><div className="text-[10px] text-gray-500">{label}</div><div className="text-lg font-bold">{value}%</div><div className="mt-1 h-1 rounded bg-white/10"><div className="h-1 rounded bg-amber-400" style={{width:`${Math.min(100,value)}%`}}/></div></div>)}</div></section>)}</div>}</main></div>; }

export function CorrectScore() { const { data=[],isLoading,refetch }=useAnalyticalMatches(); const rows=useMemo(()=> (data as any[]).map(m=>({m,scores:exactScoreDistribution(m as any)})).filter(x=>x.scores.length).slice(0,16),[data]); return <div className={shell}><main className="container max-w-6xl mx-auto px-4 py-6"><header className="flex items-center justify-between mb-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/15 p-3"><Target className="h-6 w-6 text-cyan-400"/></div><div><h1 className="text-2xl font-black text-cyan-400">PLACAR EXATO</h1><p className="text-xs text-gray-500">Poisson + ajuste Bayesiano + xG do NEXUS Core • leitura indicativa</p></div></div><button onClick={()=>refetch()} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><RefreshCw className="inline h-3.5 w-3.5 mr-1"/>Atualizar</button></header>{isLoading?<Loading/>:rows.length===0?<Empty/>:<div className="grid gap-3 md:grid-cols-2">{rows.map(({m,scores}:any)=><section key={String(m.id||m.fixture?.id)} className={card+' p-4'}><div className="mb-3 flex items-center justify-between"><div className="font-bold text-sm"><MatchName match={m}/></div><span className="text-[9px] text-gray-500">NEXUS CORE</span></div><div className="grid grid-cols-4 gap-2">{scores.map((s:any)=><div key={s.score} className="rounded-lg border border-cyan-500/10 bg-cyan-500/5 p-2 text-center"><div className="font-black text-cyan-300">{s.score}</div><div className="text-[10px] text-gray-500">{Math.round(s.probability*100)}%</div></div>)}</div></section>)}</div>}</main></div>; }

export function BetAnalyzer() { const { data=[],isLoading,refetch }=useAnalyticalMatches(); const scenarios=useMemo(()=> (data as any[]).map(m=>{const markets=analyzeMarkets(m as any).filter(x=>x.probability>0).sort((a,b)=>b.probability-a.probability);const best=markets[0];const goals=markets.filter(x=>x.category==='goals').sort((a,b)=>b.probability-a.probability)[0];const corners=markets.filter(x=>x.category==='corners').sort((a,b)=>b.probability-a.probability)[0];const cards=markets.filter(x=>x.category==='cards').sort((a,b)=>b.probability-a.probability)[0];return{m,best,goals,corners,cards};}).filter(x=>x.best).sort((a,b)=>(b.best?.probability||0)-(a.best?.probability||0)).slice(0,20),[data]); return <div className={shell}><main className="container max-w-6xl mx-auto px-4 py-6"><header className="flex items-center justify-between mb-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-orange-500/15 p-3"><Crosshair className="h-6 w-6 text-orange-400"/></div><div><h1 className="text-2xl font-black text-orange-400">BET ANALYZER</h1><p className="text-xs text-gray-500">Análise de cenários integrada ao NEXUS Core • somente analítico</p></div></div><button onClick={()=>refetch()} className="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs"><RefreshCw className="inline h-3.5 w-3.5 mr-1"/>Atualizar</button></header>{isLoading?<Loading/>:<div className="grid gap-3">{scenarios.map(({m,best,goals,corners,cards}:any)=><section key={String(m.id||m.fixture?.id)} className={card+' p-4'}><div className="flex items-center justify-between mb-3"><div className="font-bold text-sm"><MatchName match={m}/></div><span className="text-xs font-black text-emerald-400">Cenário principal {best.probability}%</span></div><div className="grid gap-2 md:grid-cols-4">{[['Principal',best],['Gols',goals],['Escanteios',corners],['Cartões',cards]].map(([label,x]:any)=><div key={label} className="rounded-xl bg-white/5 p-3"><div className="text-[10px] uppercase tracking-wider text-gray-500">{label}</div>{x?<><div className="mt-1 text-xs font-bold">{x.market}</div><div className="text-lg font-black text-emerald-400">{x.probability}%</div><div className="text-[9px] text-gray-500">{x.risk}</div></>:<div className="mt-2 text-xs text-gray-600">Sem dados</div>}</div>)}</div></section>)}</div>}</main></div>; }
